### ISSUE TITLE
Does not work as described

### ISSUE THREAD

**Issue by kalleswe** [vladmandic/nudenet#6]
Throws errors and not working as described in the example.

# node src/nudenet.js -i samples/nude.jpg -o samples/nude-out.jpg
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '@vladmandic/pilogger'
Require stack:
- /nudenet/src/nudenet.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/nudenet/src/nudenet.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/nudenet/src/nudenet.js' ]
}

**Comment by vladmandic** [comment]
did you run `npm install` first (or yarn or pnpm, depending which package manager you choose to use?
that is basic for every javascript/typescript/nodejs project.
